### ISSUE TITLE
Level j2v8 jar versions

### ISSUE THREAD

**Issue by vekexasia** [mastadonian/ArkOptimalWallet#11]
Right now here's the current situation for `j2v8` library:
![image](https://user-images.githubusercontent.com/200523/30267790-f5091ba0-96e3-11e7-80d4-95b3157444a1.png)
As you can see version `4.6.0` is used for mac and windows while 4.8.0 is being used for linux.

This could cause behavior differences between the different platforms. 

I'd suggest to use the same version for all the supported environments.

**Comment by mastadonian** [comment]
Used bitcoinj for mnemonic code generation. We can get rid of the j2v8.
