### ISSUE TITLE
Code Bracket consistency

### ISSUE THREAD

**Issue by vekexasia** [mastadonian/ArkOptimalWallet#12]
There's a lot of inconsistency in how brackets are used within the code.

Take the following snapshots:

![image](https://user-images.githubusercontent.com/200523/30267919-5b4c0cba-96e4-11e7-967a-2fa1301d10e0.png)
![image](https://user-images.githubusercontent.com/200523/30267926-62db940a-96e4-11e7-9ce9-888ff053292b.png)
![image](https://user-images.githubusercontent.com/200523/30267932-695267a0-96e4-11e7-88a9-00e49d979b65.png)

I'd suggest to use the following format:
```java
if (condition) {
   //lines
}
```
(Even for single line if blocks)

**Comment by mastadonian** [comment]
Sure :) will do!
