### ISSUE TITLE
BUG: Cannot copy ARK address

### ISSUE THREAD

**Issue by vekexasia** [mastadonian/ArkOptimalWallet#14]
I tried to click the copy btn but after the animation is complete nothing is copied to the clipboard. 

I'm referring to this:
![image](https://user-images.githubusercontent.com/200523/30268980-bff64df8-96e7-11e7-9839-4c81a178fd0e.png)

**Comment by mastadonian** [comment]
Yup, that is not developed yet. It will be part of the release.

**Comment by mastadonian** [comment]
Fixed
