### ISSUE TITLE
Limit subaccounts and account for tx fee when running optimization.

### ISSUE THREAD

**Issue by vekexasia** [mastadonian/ArkOptimalWallet#16]
Right now there is no limit on the number of subaccounts a user could have.

If I understand it correctly the user will be able to select several delegates to vote for and voting weight is spread across sub accounts so that user maximizes its ROI.

What happens if I've an account with 15 ARK and I select 15 delegates? I suspect that it could happen that a subwallet could end up with an amount lower or equal than tx fees.

I'm not a math expert but if the workflow is what I've pointed above then I'd say that preventing such behavior is a must-have for something that tries to optimize ROI for users.

**Comment by mastadonian** [comment]
The optimization for accounts with few arks would mostly result in concentrated votes for 1 delegate (fewest votes delegate). There is no issue to have as many sub wallets if they are not allocated any votes.
