### ISSUE TITLE
Use ark-java instead of custom (re)built methods

### ISSUE THREAD

**Issue by vekexasia** [mastadonian/ArkOptimalWallet#17]
I've seen `core` folder contains stuff that are already written in https://github.com/ArkEcosystem/ark-java library which I suspect being heavily tested.

Using that library will move bugs and maintenance away from this project.

**Comment by mastadonian** [comment]
Yeah! We can actually favored to rewrite non-groovy :) version of  ark-java and fill its gaps and possibly make it more comprehensive easy to use Ark-Java and may be ask the ark team to publish it.
