### ISSUE TITLE
Feature: Reflow back from subaccounts to main account

### ISSUE THREAD

**Issue by vekexasia** [mastadonian/ArkOptimalWallet#18]
I guess that if a user would want to move all of their funds it's going to be a bit complicated.

Hence I think it's actually a good idea to provide users a way to recollect subaccount funds.

**Comment by mastadonian** [comment]
Yeah. That is one of the use cases that we are working one. It will be part of this release.

**Comment by mastadonian** [comment]
Hey @vekexasia. I have added the capability to that. Regards!
