### ISSUE TITLE
Remove j2v8 dependency in favor of bitcoinj

### ISSUE THREAD

**Issue by vekexasia** [mastadonian/ArkOptimalWallet#19]
Right now the only use of j2v8 is mnemonic codes generation.

If you'd like to keep this functionality (Create new accounts) I'd strongly suggest to move away from j2v8 and use bitcoinj java library instead. -> https://bitcoinj.github.io/

Right now the code needs to "trust" 2 external components:
 -> `j2v8` to run js code in java
 -> `bip39` npm package

While, when moving to bitcoinj only you'll only have 1 point of failure. Furthermore bitcoinj is more supported and used having more than 1k stars in github.

also this would completely remove the need to fix issue #11 .

**Comment by mastadonian** [comment]
Totally agree! I briefly looked at bitcoinj for mnemonic generation but for some reason I went through with javascript native call. I fixed it now and we can get rid of the j2v8.
