### ISSUE TITLE
Remove unused and duplicated code

### ISSUE THREAD

**Issue by vekexasia** [mastadonian/ArkOptimalWallet#20]
There are several methods which are currently not used. Some of them are even showing 1:1 duplicated code.

For example: Crypto.readFileAsString is unused AND 1:1 copy of AccountService.readFileAsString (Which is also unused code)

**Comment by mastadonian** [comment]
Those unused methods are sometimes used for unit testing and will be removed with the code cleanup stage before releasing. Some will be removed momentarily.
