### ISSUE TITLE
Async/Network calls looks glitchy

### ISSUE THREAD

**Issue by vekexasia** [mastadonian/ArkOptimalWallet#9]
Apparently most (if not all) network calls are done in the same thread as UI.

This makes the app look glitchy since the rendering thread is stopped while performing a network request.

I'd suggest to use rxjava or native threads to move the network requests out of the main thread and let the app run smoothly.

**Comment by mastadonian** [comment]
I think that depends on the use case. Some network calls we require it to look like it is a sync calls. Example: retrieving account transactions, subwallet votes etc. Some transactional calls are better be async calls. In any case as part of finalizing the uses cases, we look each screen (and screen flows) and will decide which will require async vs sync-like calls.

**Comment by vekexasia** [comment]
Hello @mastadonian. The whole problem is caused by async calls being made in ui thread. This causes the app to briefly freeze.

**Comment by mastadonian** [comment]
Hey @vekexasia, yeah I am using the storage service to fork a couple of daemon threads to update the whole wallet. That made the UI very smooth. I will push the change to the github shortly.
